### ISSUE TITLE
example doesn't work in Pyspark for spark 1.5+ 

### ISSUE THREAD

**Issue by harishkashyap** [databricks/spark-xml#68]
File "/opt/cloudera/parcels/CDH-5.5.0-1.cdh5.5.0.p0.8/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 121, in load
  File "/opt/cloudera/parcels/CDH-5.5.0-1.cdh5.5.0.p0.8/lib/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/opt/cloudera/parcels/CDH-5.5.0-1.cdh5.5.0.p0.8/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 36, in deco
  File "/opt/cloudera/parcels/CDH-5.5.0-1.cdh5.5.0.p0.8/lib/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o51.load.
: java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;
	at com.databricks.spark.xml.XmlOptions$.createFromConfigMap(XmlOptions.scala:45)
	at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:57)
	at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:43)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:125)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:114)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kur1j** [comment]
Just ran into this exact issue with HDP 2.3.2 which comes with Spark 1.4.1. It appears to be a problem with Scala 2.11. 

Temporary fix is to recompile Spark-xml with 2.10.6.

In build.sbt change the following.
//scalaVersion := "2.11.7"
scalaVersion := "2.10.6"

https://groups.google.com/forum/#!topic/adam-developers/j5bzgpK5-aU

**Comment by harishkashyap** [comment]
Thanks @kur1j for quick reply. That would be tough for our prod environment. Will look out for the new release.

**Comment by HyukjinKwon** [comment]
Thanks, @kur1j. 
@harishkashyap Have you tried this as well with  not **2.11** but **2.10**?

```bash
pyspark --packages com.databricks:spark-xml_2.10:0.3.1
```

**Comment by harishkashyap** [comment]
That works! thanks @HyukjinKwon

**Comment by HyukjinKwon** [comment]
Cool!
