### ISSUE TITLE
spark-2.3 doesn't recognize .xml()

### ISSUE THREAD

**Issue by ganeshchand** [databricks/spark-xml#328]
The `.xml()` syntax doesn't work on Spark 2.3. 

```
sqlContext.read
  .option("rowTag", "book")
  .xml("/book.xml")
```
The above code gives the following error:
```
value xml is not a member of org.apache.spark.sql.DataFrameReader
possible cause: maybe a semicolon is missing before `value xml'?
  .xml("/book.xml")
```
In Spark 2.3, you must use `.format("xml")` and `.load()`.

```
spark
.read
.format("xml")
.option("rowTag","catalog")
.load("/mnt/tmp/book.xml")
```

**Comment by srowen** [comment]
You'll need to import the implicit to get this method:
`import com.databricks.spark.xml._`
