### ISSUE TITLE
Support for writing attributes

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/spark-xml#41]
Currently, writing XML files with this library does not support to write attributes.
It would be great if we can write some attributes through this library.

I am thinking both ways for this.
First is to make some options to designate which one should be treated as attribute.
Second is to use prefix for attributes such as `_` or `@` for both reading and writing so that we can differentiate elements and attributes easily.

**Comment by HyukjinKwon** [comment]
I think might have to resemble `dicttoxml` python library.

**Comment by HyukjinKwon** [comment]
Fixed in https://github.com/databricks/spark-xml/pull/43.

**Comment by harishkashyap** [comment]
gosh! I would need this too! turns out I can't in older version. @HyukjinKwon look forward to next version of this supporting pyspark 1.5+

**Comment by HyukjinKwon** [comment]
@harishkashyap Actually, I merged this already and released 0.3.1.

As you might know, I described the structure conversion [here](https://github.com/databricks/spark-xml#conversion-from-xml-to-dataframe).

So... if you need to create attributes to output XML files, then you might need to add some fields as the structure below:

```
root
 |-- two: struct (nullable = true)
 |    |-- #VALUE: string (nullable = true)
 |    |-- @myTwoAttrib: string (nullable = true)
 |-- three: string (nullable = true)
```

then you might write a XML file
```scala
df.write
    .format("com.databricks.spark.xml")
    .option("rowTag", "one")
    .save("tmp.xml")
```

which creates a XML below:

```xml
...
<one>
    <two myTwoAttrib="BBBBB">two</two>
    <three>three</three>
</one>
...
```

If you are intended to create some elements with child elements, then you might need to create some fields as below:

```
root
 |-- @myOneAttrib: string (nullable = true)
 |-- two: string (nullable = true)
 |-- three: string (nullable = true)
```

then you might write a XML file
```scala
df.write
    .format("com.databricks.spark.xml")
    .option("rowTag", "one")
    .save("tmp.xml")
```

which creates a XML below:

```xml
...
<one myOneAttrib="AAAA">
    <two>two</two>
    <three>three</three>
</one>
...
```

I understand this might be a bit confusing but it is inevitable due to the differences of structures between XML and `Dataframe`.

If it does not work, then, it should be an issue.

**Comment by harishkashyap** [comment]
Thanks @HyukjinKwon. I am trying to get his working on pyspark 1.5+. Is that issue resolved?

**Comment by harishkashyap** [comment]
Oh are you saying the 0.3.1 on older version works?

**Comment by HyukjinKwon** [comment]
Yes, this 0.3.1 should work on all the Spark versions 1.3+.
Would you describe your environment a bit more if you are hitting some issues to run this library? 
I would like to reproduce if this 0.3.1 does not work on Spark (including pyspark) versions 1.3+.

**Comment by harishkashyap** [comment]
@HyukjinKwon as I already mentioned the example on the home page with books.xml doesn't work with the latest version spark 1.5+. It doesn't load.

**Comment by harishkashyap** [comment]
File "/opt/cloudera/parcels/CDH-5.5.0-1.cdh5.5.0.p0.8/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 121, in load
  File "/opt/cloudera/parcels/CDH-5.5.0-1.cdh5.5.0.p0.8/lib/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/opt/cloudera/parcels/CDH-5.5.0-1.cdh5.5.0.p0.8/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 36, in deco
  File "/opt/cloudera/parcels/CDH-5.5.0-1.cdh5.5.0.p0.8/lib/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o48.load.
: java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;
	at com.databricks.spark.xml.XmlOptions$.createFromConfigMap(XmlOptions.scala:45)
	at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:57)
	at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:43)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:125)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:114)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:745)

**Comment by HyukjinKwon** [comment]
I see. I thought https://github.com/databricks/spark-xml/issues/41#issuecomment-173797086 says it's working okay with Spark 1.5+. 

Hm.. I have tried this and it looks fine with Spark 1.5+. Maybe I will try this with the same environment with you. I guess you are using Cloudera CDH VM. I will try.

**Comment by harishkashyap** [comment]
No #68 is referring to an older version. In that version I can read but not write attributes.
